# config.py

DEFAULT_VALUES = {
    "hourly_predictions_file": "examples/data/phase_1/phase_1_transformer_25200_1h_prediction.csv",
    "daily_predictions_file": "examples/data/phase_1_daily/phase_1_transformer_25200_1d_prediction.csv",
    "uncertainty_hourly_file":"examples/data/phase_1/phase_1_transformer_25200_1h_uncertanties.csv",
    "uncertainty_daily_file": "examples/data/phase_1_daily/phase_1_transformer_25200_1d_uncertanties.csv",
    "base_dataset_file": "examples/data/phase_1/phase_1_base_d3.csv",
    #"hourly_predictions_file": None,
    #"daily_predictions_file": None,
    #"uncertainty_hourly_file":None,
    #"uncertainty_daily_file": None,
    
    "date_column": "DATE_TIME",
    "plugin": "default",
    "time_horizon": 6,
    "population_size": 5,
    "num_generations": 10,
    "crossover_probability": 0.5,
    "mutation_probability": 0.2,
    "load_config": None,
    "save_config": "config_out.json",
    "remote_log": None,
    "remote_load_config": None,
    "remote_save_config": None,
    "username": None,
    "password": None,
    "save_log": "debug_log.json",
    "quiet_mode": False,
    "force_date": False,
    "headers": True,
    "disable_multiprocessing": True,
    #output files for balance plot, trades csv and summary in a csv with all possible statistics
    "balance_plot_file": "balance_plot.png",
    "trades_csv_file": "trades.csv",
    "summary_csv_file": "summary.csv",
    "strategy_name": "Heuristic Strategy",
    "max_steps": 6300,
    "save_parameters": "parameters.json",
    "load_parameters": None,
    #"use_normalization_json": "tests/data/phase_1/phase_1_normalizer_debug_out.json",
    "use_normalization_json": None,
    "default_uncertainty_short_term": 0.003,
    "default_uncertainty_long_term": 0.005,
    "daily_columns": ["Prediction_H24", "Prediction_H48", "Prediction_H72", "Prediction_H96", "Prediction_H120", "Prediction_H144"],
    "hourly_columns": ["Prediction_H1", "Prediction_H2", "Prediction_H3", "Prediction_H4", "Prediction_H5", "Prediction_H6"],
    "uncertainty_daily_columns": ["Uncertainty_H24", "Uncertainty_H48", "Uncertainty_H72", "Uncertainty_H96", "Uncertainty_H120", "Uncertainty_H144"],
    "uncertainty_hourly_columns": ["Uncertainty_H1", "Uncertainty_H2", "Uncertainty_H3", "Uncertainty_H4", "Uncertainty_H5", "Uncertainty_H6"]
    
     
}
