#!/bin/bash
bash heuristic.sh --predictor_daily_config_file examples/config/phase_2_daily/phase_2_5_ann_1d_config.json --predictor_hourly_config_file examples/config/phase_2/phase_2_5_ann_1h_config.json --base_dataset_file examples/data/phase_3/base_d6.csv --load_parameters examples/results/phase_3_2_daily/phase_3_2_cnn_25200_1d_results_high_frequency_parameters.json --prefix _high_frequency --max_trades_per_5days 20
bash heuristic.sh --predictor_daily_config_file examples/config/phase_2_daily/phase_2_5_ann_1d_config.json --predictor_hourly_config_file examples/config/phase_2/phase_2_5_ann_1h_config.json --base_dataset_file examples/data/phase_3/base_d6.csv --load_parameters examples/results/phase_3_2_daily/phase_3_2_cnn_25200_1d_results_low_frequency_parameters.json --prefix _low_frequency --max_trades_per_5days 3
bash heuristic.sh --predictor_daily_config_file examples/config/phase_2_daily/phase_2_5_cnn_1d_config.json --predictor_hourly_config_file examples/config/phase_2/phase_2_5_cnn_1h_config.json --base_dataset_file examples/data/phase_3/base_d6.csv --load_parameters examples/results/phase_3_2_daily/phase_3_2_cnn_25200_1d_results_high_frequency_parameters.json --prefix _high_frequency --max_trades_per_5days 20
bash heuristic.sh --predictor_daily_config_file examples/config/phase_2_daily/phase_2_5_cnn_1d_config.json --predictor_hourly_config_file examples/config/phase_2/phase_2_5_cnn_1h_config.json --base_dataset_file examples/data/phase_3/base_d6.csv --load_parameters examples/results/phase_3_2_daily/phase_3_2_cnn_25200_1d_results_low_frequency_parameters.json --prefix _low_frequency --max_trades_per_5days 3
bash heuristic.sh --predictor_daily_config_file examples/config/phase_2_daily/phase_2_5_lstm_1d_config.json --predictor_hourly_config_file examples/config/phase_2/phase_2_5_lstm_1h_config.json --base_dataset_file examples/data/phase_3/base_d6.csv --load_parameters examples/results/phase_3_2_daily/phase_3_2_cnn_25200_1d_results_high_frequency_parameters.json --prefix _high_frequency --max_trades_per_5days 20
bash heuristic.sh --predictor_daily_config_file examples/config/phase_2_daily/phase_2_5_lstm_1d_config.json --predictor_hourly_config_file examples/config/phase_2/phase_2_5_lstm_1h_config.json --base_dataset_file examples/data/phase_3/base_d6.csv --load_parameters examples/results/phase_3_2_daily/phase_3_2_cnn_25200_1d_results_low_frequency_parameters.json --prefix _low_frequency --max_trades_per_5days 3
bash heuristic.sh --predictor_daily_config_file examples/config/phase_2_daily/phase_2_5_transformer_1d_config.json --predictor_hourly_config_file examples/config/phase_2/phase_2_5_transformer_1h_config.json --base_dataset_file examples/data/phase_3/base_d6.csv --load_parameters examples/results/phase_3_2_daily/phase_3_2_cnn_25200_1d_results_high_frequency_parameters.json --prefix _high_frequency --max_trades_per_5days 20
bash heuristic.sh --predictor_daily_config_file examples/config/phase_2_daily/phase_2_5_transformer_1d_config.json --predictor_hourly_config_file examples/config/phase_2/phase_2_5_transformer_1h_config.json --base_dataset_file examples/data/phase_3/base_d6.csv --load_parameters examples/results/phase_3_2_daily/phase_3_2_cnn_25200_1d_results_low_frequency_parameters.json --prefix _low_frequency --max_trades_per_5days 3


echo "All configurations processed."
